### PR TITLE
update FreeDOS kernel to 2043

### PR DESCRIPTION
**Pull request by PerditionC**
FreeDOS kernel 2043 has been released, this one was compiled today and added to kernel release as ke2043_rufus.zip - it is compiled for 386 with FAT32 support and FORCELBA set to enabled.  Full source is the ke2043 tagged branch on GitHub FDOS\kernel   Rufus is what I usually use to make my bootable USB drives :-)   (If you are interested I will send you a PR in a week or so after FreeCom 0.85 is released).

### CODE REVIEW

**Comment by pbatard** [comment]
> FreeDOS kernel 2043 has been released

Great!

Could you please also announce this on the FreeDOS mailing list? The last message I see from you on that topic (dated 2021.05.03) is:

> I will be making a new kernel release as soon as I can. (...) I'm aware it's late in release, so these may just be post release updates.

Or was that message akin to a release announcement, since you effectively published your kernel binaries about 10 days later?

Also, does the last part imply that this kernel may not be part of upcoming FreeDOS 1.3 release?

My plan with Rufus has currently been to stick with the kernel used in formal FreeDOS releases, in order to avoid any potential _"When I run DOS application X with Rufus it behaves this way, but when I run it with the last FreeDOS release, it behaves that way"_ issues, and I've been kind of waiting to see what 1.3 actually includes to make a move on updating my kernel... which of course depends on FreeDOS 1.3 reaching release stage.

> this one was compiled today and added to kernel release as ke2043_rufus.zip - it is compiled for 386 with FAT32 support and FORCELBA set to enabled.

Thanks for doing this. But I think I'll still prefer to pick the standard kernel release binary and flip the `FORCELBA` bit myself, so that people can validate that the what we provide as a binary in Rufus is exactly the same as formal FreeDOS', except for that bit. Else, I expect the recompilation to alter more than the `CONFIG` section, which always leads to people having doubts on whether they can actually trust our binary...

In other words, provided FreeDOS 1.3 is based on the `kernel.zip` package from your `ke2043` release, I'm still planning to pick `KERNL386.SYS` from that archive and alter byte `0x000D`, instead of using the one from your `ke2043_rufus.zip` (which I appreciate, but which, unless there's more than editing byte `0x000D` to enable LBA, you can actually remove from your release).

Also, at this stage, I expect Rufus 3.15 to be released after FreeDOS 1.3. So I am planning to only update kernel/FreeCOM once that has happened, and also so that I can update other stuff like `KEYB.EXE` or `MODE.COM` if needed.

So I will keep this PR opened for now, and address is when I'm nearing Rufus 3.15 release. 

And please do post release announcements for kernel and FreeCOM on the mailing list (no need to send me another PR), as these are rather critical pieces that I think deserve their own notifications when updated. Especially, I don't expect to be the only one from the mailing list who would like to see these kind of milestones publicized...

**Comment by marcosfrm** [comment]
Binary boot records are not distributed anymore? For example, the old [kernels.zip](http://ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.0/pkgs/kernels.zip) from FreeDOS 1.0 has `source/ukernel/boot/fat32lba.bin`. Compared to the [ke2043s.zip](https://github.com/FDOS/kernel/releases/download/ke2043/ke2043s.zip) version (`nasm SOURCE/ke2043/boot/boot32lb.asm -ofat32lba.bin`) it differs:

```
--- fat32lba_bin_old    2021-11-03 12:39:56.670006471 +0000
+++ fat32lba_bin_new    2021-11-03 12:43:33.860006831 +0000
@@ -5,8 +5,8 @@
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
-  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
-  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xfc, 0xfa, 0x29, 0xc0, 0x8e, 0xd8,
+  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46, 0x41,
+  0x54, 0x33, 0x32, 0x20, 0x20, 0x20, 0xfc, 0xfa, 0x29, 0xc0, 0x8e, 0xd8,
   0xbd, 0x00, 0x7c, 0xb8, 0xe0, 0x1f, 0x8e, 0xc0, 0x89, 0xee, 0x89, 0xef,
   0xb9, 0x00, 0x01, 0xf3, 0xa5, 0xea, 0x7a, 0x7c, 0xe0, 0x1f, 0x00, 0x00,
   0x60, 0x00, 0x8e, 0xd8, 0x8e, 0xd0, 0x8d, 0x66, 0xe0, 0xfb, 0x88, 0x56,
```

Should [ms-sys](https://sourceforge.net/p/ms-sys/code2/) (used by Rufus) get these changes?

**Comment by pbatard** [comment]
Again, I am not planning to update any of the FreeDOS binaries from Rufus unless there is a __formal__ release of FreeDOS that uses these binaries. Thus, I am still waiting to see FreeDOS 1.3 being officially released before I touch anything.

Unless there is a major bug to fix, working with pre-release software is just not worth the trouble...

**Comment by pbatard** [comment]
Well, seeing that there is still no formal release of FreeDOS happening on the horizon (note: this is not a complaint &mdash; I know these things take time), and considering that I am subscribed to the FreeDOS mailing list, so I will know when I can update the kernel used by Rufus with the one from the latest official release, I'm just going to close this PR.

**Comment by pbatard** [comment]
Reopening this PR on account that FreeDOS 1.3 has just been released (congrats on all the good work that led to the release by the way! 😄) and I will therefore update the Kernel used by Rufus to version 2043 through, a commit that will close and reference this.

**Pull request closed without merging**
