### PR TITLE
Fix ortographic errors

### PR DESCRIPTION
**Pull request by trinaldi**
An user - Ricardo Pereira da Costa - contacted me and suggest/show me some fixes.

### CODE REVIEW

**Comment by pbatard** [comment]
Applied. Thank you very much!

**Comment by trinaldi** [comment]
Pete, let me ask you.

When someone suggests a change, should I edit right away or wait for some
kind of review?

Thanks

**Comment by pbatard** [comment]
Hi Tiago, sorry for the late reply. How and when you submit it is pretty much up to you, as I'm not really in a position to review changes for languages that I don't speak. Generally speaking, I prefer if a series of changes for a specific translation are grouped into a single commit, but it's not a big deal if they aren't. But it's really up to you to decide what you think is best. Thanks.

**Comment by NickeManarin** [comment]
I speak Portuguese and I agree with this changes.

**Pull request closed without merging**
