### PR TITLE
Update ru-RU.po

### PR DESCRIPTION
**Pull request by ViktorOn**

### CODE REVIEW

**Comment by pbatard** [comment]
Thanks, but please note that I'm going to defer all translation updates until I start a new translation round (which will probably be a couple months from now). I will refer your changes to the official Russian translator then so that they can validate them.

**Comment by ViktorOn** [comment]
> Thanks, but please note that I'm going to defer all translation updates until I start a new translation round (which will probably be a couple months from now). I will refer your changes to the official Russian translator then so that they can validate them.

No problem, as you please

**Comment by s4nflower** [comment]
1133:
Однако мы не будем раскрывать _какие-любо_ личные данные третьим сторонам
Однако мы не будем раскрывать какие-**либо** личные данные третьим сторонам

**Comment by pbatard** [comment]
Hi Viktor,

Are you still willing to help with the Russian translation update?
I have now finalized the message updates for the next release (please be mindful that some one the messages you already translated might have changed) and have started a new translation round.

The list of changes from 3.5 to 3.22 can be found [here](https://github.com/pbatard/rufus/blob/master/res/loc/ChangeLog.txt#L8-L83).

Also, if you e-mail me to: pete@akeo.ie, I can send you the e-mail I sent all the translators, that contains additional updates with regards to these new updates.

Thanks.

**Comment by ViktorOn** [comment]
> Hi Viktor,
> 
> Are you still willing to help with the Russian translation update? I have now finalized the message updates for the next release (please be mindful that some one the messages you already translated might have changed) and have started a new translation round.
> 
> The list of changes from 3.5 to 3.22 can be found [here](https://github.com/pbatard/rufus/blob/master/res/loc/ChangeLog.txt#L8-L83).
> 
> Also, if you e-mail me to: [pete@akeo.ie](mailto:pete@akeo.ie), I can send you the e-mail I sent all the translators, that contains additional updates with regards to these new updates.
> 
> Thanks.

Hi! I am ready to help in general, but now I'm not up to it. Difficulties in life, no time for hobbies.

**Comment by pbatard** [comment]
No worries, I should be able to find a new translator for Russian and I hope your difficulties in life will ease up.

I'll close this PR without applying it then, because some of the new messages have evolved since last July, and I don't want to end up with parts of the translation that don't quite match the English version. Still, I'll try to point out any new Russian translator to your proposal, so that your work isn't wasted.

**Pull request closed without merging**
