### PR TITLE
typo twice faster than

### PR DESCRIPTION
**Pull request by LLyaudet**

### CODE REVIEW

**Comment by pbatard** [comment]
I'm not seeing much of a typo to correct there.
_"twice as fast as"_ seems to be [good enough for BBC reporters](https://www.bbc.com/news/world-us-canada-47754189), which is also good enough for me. ;)

&rarr; Rejected.

**Comment by pbatard** [comment]
Don't take it personally but, between a random non-native English speaker that I've never met, and a BBC article that I expect to have been reviewed before publishing (because that's how web publishing from professional sources like the BBC goes), I'll trust the BBC article by a long mile when it comes to grammatical correctness...

**Comment by LLyaudet** [comment]
No problem. I clearly understand your point of view. My answer was just to point out that as a native French-speaker, I know from experience that even French professional sources reference journals like "Le Monde" that are also reviewed before publishing have frequently grammar or orthographic errors. The number of errors, wrote or spoken, being clearly more important with TV journalists. I expect the language level of journalists to be the same whatever the language/country.

**Comment by pbatard** [comment]
What you fail to understand is that I used the BBC article as one of the numerous examples I could find of usage of "twice as fast as". If you had done your research, you would have found that using "twice as fast as" does not qualify as a typo at all, and Google clearly indicates that the usage of "twice as fast as" is exceedingly common, compared to "twice faster than" (with, actually, most of the search results I see for "twice faster than" being from people __discouraging__ its use as something that doesn't sound natural to a native English speaker).

The thing is, your phrasing of "twice faster than" did feel very unnatural to me, but (unlike what seems to be your case if you're still trying to "demonstrate" that you are somehow more trustworthy than a public BBC article) I considered that I could be wrong, and therefore ran a quick search to validate that "twice as fast as" is clearly not grammatically incorrect and also something that is widely used by native English speakers. And since the BBC article had the construct in its title, I picked that one as an example to prove my point.

Please just accept that you were wrong and move on instead of grasping at straws as to how you may still somehow have been right. It's not the end of the world.

**Comment by LLyaudet** [comment]
I have no problem admitting I am wrong. My first answer had a ';)' smiley. My second answer started with "No problem. I clearly understand your point of view."...

What I mean by "your point of view" is not the fact that it is not a typo. I believe you for this. 
I mean your point of view that a random non-native English speaker should not be trusted against a BBC article.
I was just joking on the fact that many persons/journalists native speakers of @insert_some_random_language_here@ are just plain wrong when it comes to grammar and other languages skills. So the BBC or Google argument of authority is quite funny, even if I trust you that it yields a correct answer in this case. Let me illustrate with a common error I hear on the French TV quite frequently : 
Error of the journalists :
  - "Le premier ministre a donné une allocation ce matin."
  - Translation : "The prime minister gave a benefit this morning."
"allocation chômage" = "unemployment benefit", etc.
The word "allocation" is common.
Correct sentence :
 - "Le premier ministre a donné une allocution ce matin."
 - Translation : "The prime minister gave a speech this morning."
The word "allocution" is more literate.
There is just one letter between "allocation" and "allocution" but the meaning is totally different.
Some errors become so common that they may become the correct use in a few centuries.

I apologize if I sounded arrogant or unfriendly. At first, when I submitted the PR I thought I was right and the messages after were just because my parents educated me with word play and joking about the misuse of words and a lot of journalists misuse words (most of the time unintentionally). So I somewhat clumsily tried to communicate this kind of joking on misuse of words and joking on journalists in general (I repeat that I admit my error on this particular case.) I admit it is not very clever of making fun of unintentional misuse of words by some people. This is just a mindset I inherited from my parents. At least, if you learn French some day, I can advise you to look in a dictionary or in Grevisse "Le bon usage" and trust these references more than TV, journals or even the majority of French people.

Best regards and sorry for the trouble,
    Laurent Lyaudet

**Comment by pbatard** [comment]
> I mean your point of view that a random non-native English speaker should not be trusted against a BBC article.

C'est une vision tres reduite du probleme. Mon probleme est que ma connaissance de l'Anglais (qui n'est pas ma langue maternelle, car c'est en fait... le Francais) m'indiquait que votre suggestion etait erronnee, et l'article de la BBC servait juste a corroborer mon impression. Et j'ai clairement aussi indique le fait que les articles de la BBC (mais vous pouvez aussi essayer de disputer ca si vous le voulez) etaient revus par une tierce personne avant publication, conformement a la pratique journalistique courante. Et, contrairement a ce que vous sembler pensez, je ne peux que disputer votre hypothese douteuse qui stipule que, parce que la BBC est a l'origine une chaine de television, leur professionnalisme journalistique ecrit doit etre considere comme n'appliquant pas l'un des principes de bases de la matiere, a savoir la revision des copies par une tierce personne (en general un editeur dedie a cette tache) avant publication.

Donc, a moins que vous ne puissiez __demontrer__ le contraire, on ne peut que considerer que, statistiquement, les articles publies sur le site de la BBC ont ete revus par au moins deux personnes, dont, la encore statistiquement, l'Anglais est vraisemblablement la langue natale. Ce qui me donne logiquement le droit de considerer n'importe quel article publie par le BBC comme beaucoup plus fiable, en terme de tournures grammaticales, qu'une tierce personne dont l'Anglais n'est pas la langue maternelle. C'est une simple question de logique.

Maintenant, vous pouvez continuer a donner des __anectodes__ comme quoi, dans un nombre de cas limites, certains articles publies par des journalistes, autrement reputes, contiennent des coquilles ou fautes de Francais ou d'Anglais, mais cela restera toujours anectotal, auquel cas la logique de persomption qu'un article de la BBC vaut mieux en terme d'autorite sur les tournures de phrases anglaises que l'avis d'une tierce personne dont l'Anglais n'est pas la langue natale.

En resume, votre raisonnement part du principe que tout individu doit exhiber un manque de confiance implicite vis a vis de la capacite d'une certaine categorie de journalistes (par simple mesure de leur association avec une chaine de television, et independamment de leur parcours __probable__ de journalistes d'expression ecrite plutot qu'audiovisuelle) a produire des articles dont l'ortographe et la grammaire refletent le bon usage de la langue courante.

Malheureusement pour vous, ce n'est pas un raisonement dans lequel je peux vous suivre. Dans l'absence d'indications contraires (et j'espere que vous avez l'esprit suffisamment ouvert pour comprendre que quelques exemples anecdotaux ne se substituent pas a une tendance generale), je continuerai toujours a estimer que les articles de la BBC sont beaucoup fiable, au point de vue grammatical, qu'un tiers commentateur sur internet.

Et pour la petite info, ayant passe une bonne partie de ma vie en France, je ne me souviens pas avoir entendu ou lu des journalistes utiliser "allocation" au lieu d' "allocution". Il est evidemment possible que le niveau des journalistes ait change depuis que j'ai quitte la France, mais j'ai quand meme de serieux doutes a ce sujet, specialement quand une recherche Google rapide ne semble pas me pointer sur des articles ecrits ou "allocation" est utilise au lieu d' "allocution (ce qui, une fois de plus, semble confirmer mon assertion que les articles ecrits par des organismes reputes tels que la BBC, sont revises par plusieurs personnes afin d'eviter ce genre d'erreurs faciles a detecter).

Mon "bon usage" a moi reste donc avec le references que je vois de la BBC ou d'ailleurs, specialement quand elles apparaissent corroborer ma connaissance deja existante de certaines tournures anglaises...

**Comment by LLyaudet** [comment]
Bonjour,

Je ne pensais pas que mes excuses allaient vous énerver davantage.
Vos réponses sont nettement plus agressives que les miennes.
Je peux vous assurer que mes deux parents et moi entendons fréquemment des erreurs de français dans la bouche de journalistes dont le lapsus allocation-allocution qui ne vous a pas amusé... dommage !
Les erreurs de langage ne sont pas bien graves et, je le répète, un sujet d'amusement futile pour moi.
Pour moi au même titre que les informaticiens font parfois des bugs,
les journalistes font aussi parfois des fautes de langage.

J'ai un doctorat en informatique de l'École Normale Supérieure de Lyon et j'ai publié plusieurs articles en anglais.
J'ai lu un bien plus grand nombre d'articles.
Les typos ou erreurs de raisonnement dans les articles publiés avec revue éditoriale du journal existent malheureusement de manière assez fréquente.
Dans la plupart des cas, il n'est pas bien difficile de corriger les preuves mais je peux vous assurer qu'un solide esprit critique est nécessaire pour lire un article qu'il y ait un processus de revue éditoriale ou non.
Le processus éditorial est très loin d'être infaillible.

Cordialement,
     Laurent Lyaudet

**Comment by pbatard** [comment]
Encore une fois, vous essayez de me faire dire ce que je n'ai pas dit.

Je ne dis pas que les articles sur les sites d'information doivent etre consideres comme denues de fautes.
Je dis simplement que je doute que vous ayez une personne qui revise ce que vous ecrivez afin de detecter des possibles fautes d'ortographe our de grammaire, ce qui est la raison pour laquelle vous avez essayer de "corriger" une typo qui n'existait pas. Donc, en depit de votre parcours, a moins que vous ayez des informations specifique sur un manque de professionalisme du site d'information de la BBC, je considererai toujours que les articles publies sur ce site doivent etre consideres comme faisant preuve d'une meilleure maitrise de l'anglais que la votre (ou que n'importe quel autre commentateur tiers sur internet), car ils sont logiquement soumis a un standard de publication plus pousse que celui du commentaire individuel sur les sites social.

De surcroit, et cela ne semble helas pas vous avoir tape a l'oeil, il me semble pouvoir clairement demontrer l'application d'un esprit critique lors de l'analyse de votre suggestion, puisque ma demarche, bien que votre tournure me semblait non courante, a ete de __valider__ ma supposition en la corroborant par la recherche d'articles qui demontraient l'usage grandement repandu de "twice as fast as", dans le cas ou, puisque je ne suis pas aussi une personne dont l'anglais est la langue maternelle, mon impression initiale se serait avere erronee.

Donc, que le processus editorial soit infaillible ou non, quand 3 personnes (minimum) semblent s'accorder sur tel ou tel usage de la langue (sachant que, puisque que je ne pensais certainement pas que cela allait devenir un point contentieux et que vous auriez une aversion innee pour des sources envers lesquelles, a moins d'informations specifiques contraires et en depit d'anecdotes qui sont loin de refleter une tendance, on ne peut que donner le benefice de fiabilite au point de vue de l'usage de la langue), l'esprit critique me dit que j'ai logiquement effectue assez de recherches pour pouvoir trancher. Et, je me dois de reiterer, puisque je ne pensais que vous offrirez une telle reticence a la capacite des journalistes de la BBC de produire des articles ou l'usage de la langue anglaise peut __en general__ etre considere comme une reference, je n'ai fourni qu'un seul des liens vers tous les articles que j'aurais pu produire.

A ce stade, je ne peux que constater que, malgre votre parcours, vous semblez manifestement irrite d'avoir vu votre autorite contestee. Je ne doute pas que sur certains sujets elle soit competente, mais, helas, si je m'en refere a votre suggestion et au fait qu'une expression aussi courante que "twice as fast as" (qui, je ne peux qu'assumer, apparait frequemment dans les articles scientifiques anglais) vous semble incorrecte, je ne peux que continuer a rester confiant dans un raisonnement qui accorde de facto plus de credit a n'importe quel article de la BBC qu'a un commentateur isole sur internet, y compris un commentateur ayant votre niveau d'etude. Que l'on puisse bien evidemment trouver des exemples ponctuels contraires ici ou la ne diminue pas le sens de mon propos .

En l'occurence, puisqu'il devrait etre manifeste que j'ai du effectuer une recherche afin de trouver le lien que j'ai fourni, je ne peux qu'avoir un probleme avec le fait que vous semblez assumer que cet esprit critique qui vous est cher ne doit pas exister chez les autres, et que je me suis arrete au premier article que j'ai trouve, puisqu'autrement, je ne pense pas que vous seriez parti sur une tirade dans laquelle les articles de news seraient loin d'etre une reference du point de vue linguistique. Donc je de dois de reiterer, pour la petite info, que le fait que la formule en question apparaisse dans le titre de l'article n'est pas un hasard, et que, si votre esprit d'analyse est aussi aguerri que votre esprit critique, vous devriez vous douter que j'ai valide l'usage de cette tournure dans plus que la source de la BBC, avant de la selectionner comme __exemple non exhaustif__.

Tout cela pour dire que votre critique ne tient tout simplement pas la route. Vous assumez une demarche qui n'a clairement pas ete la mienne (par exemple en forcant l'interpretation de mes propos en une sorte d'acceptance aveugle qu'une publication sur tel ou tel medium puisse etre denuee de fautes) pour ensuite venir faire une critique generale qui n'a qu'un lien tenu avec le probleme de base, a savoir qu'en depit d'incidents ponctuels facilement identifiables, les articles de la BBC sont une bien meilleure authorite sur l'usage de l'anglais que vous et moi ne le seront jamais, et donc que vos recrimminations issues du lien que j'avais utilise pour corroborrer mes propos, sont sans fondement.

**Comment by JonnyTech** [comment]
As a native English speaker, I confirm that "_twice as fast as..._" is a commonly used term and easier understood, although "_twice faster than..._" does technically sound correct it is not commonplace and does seem rather unnatural.

**Comment by LLyaudet** [comment]
Une fois de plus vous prétendez savoir mieux que moi mes intentions. En gros, vous me traitez de menteur et je pense exactement la même chose de vos insinuations. Vous faîtes exprès d'ignorer un smiley clin d'oeil qui dénote de manière **factuelle** une ironie dans mon propos. Vous prétendez que mon expérience des erreurs journalistiques, dont mes propres parents sont témoins, n'existe pas, ce qui me fait penser à du gaslighting. Ma mère a lu quotidiennement le journal Le Monde pendant des années. Elle a arrêté ces dernières années non sans avoir eu l'occasion avant de me montrer des fautes : de français, ou factuelles ou même de vulgaire copier-coller avec une phrase répétée (et je ne parle pas de mise en exergue stylistique), ou bien des morceaux de phrase sans verbe et sans point à la fin qui suggérait une erreur de copier-coller avec une partie du texte déplacé perdue. Ce sont des preuves papier. La politique de publication des journaux en ligne la plus courante ne présente pas l'historique des corrections faites sur un article après la première publication sauf dans le cas d'erreurs factuelles graves (en théorie). Achetez des journaux papiers et vous n'aurez aucun mal à trouver des typos ou pires car aucun lecteur attentif n'aura pu faire corriger votre copie propre contrairement à ce qui se passe pour une édition électronique. J'ai mentionné mon parcours car j'ai aussi relu des articles dans ce cadre et je connais donc le processus éditorial de l'intérieur en tant qu'auteur et aussi en tant que referee. Si vous acceptez de prendre en compte certains autorités mais pas mon expérience, je maintiens que c'est un problème de sens critique. Les relecteurs sont des humains qui manquent souvent de temps. Sur des articles avec 2 ou 3 referees dont moi, il m'est arrivé d'être le seul à découvrir une erreur dans l'article soumis à publication. C'est factuel.

**Comment by pbatard** [comment]
> Si vous acceptez de prendre en compte certains autorités mais pas mon expérience, je maintiens que c'est un problème de sens critique.

Non. C'est une simple histoire de logique. Je n'ai toujours rien qui me laisse a penser, en dehors de vos propre dires, et en depit d'un aplomb qui vous a laisse penser qu'une tournure anglaise tout a fait courante etait une typo necessitant une correction, que vous puissiez etre une meilleure autorite au point de vue grammaire et orhographe qu'une source journalistique courrante.

Et apparemment, le fait de voir votre autorite mise ouvertement en question vous horripile.

Toutefois, le fait que vous n'ayez meme pas pris le peine, avant de declamer publiquement qu'il existait une typo, de verifier si:
1. Le texte que vous souhaitiez corriger etait reellement une typo
2. La correction que vous vouliez y apporter etait d'un usage courant

indique que votre autorite sur la matiere est en passe d'etre questionnee.

Et pour votre information, vous generalisez encore un propos que je n'ai pas dit. J'ai juste indique que je ne me souvenais pas avoir jamais lu ou vu ecrit l'utilisation de "allocation" au lieu de "allocution". Je ne dis absolument pas, comme vous cherchez a l'insinuer, que les erreurs journalistiques n'existent pas.

En gros, je dispute a la fois l'exemple que vous avez fourni comme cas concret d'erreur journalistique (d'autant plus que j'ai cherche a en trouver des examples avant de disputer cela) ainsi que votre professionalisme en matiere de donneur de lecon d'orthographe ou de grammaire, en me basant sur les 2 points elabores ci dessus.

Et je contraste ce clair exemple de manque de professionalisme avec celui __que l'on est en droit d'attendre__ de sources dont modus operandi est la publication d'articles, pour indiquer que, meme si l'on peut y trouver des coquilles, je suis en droit de preferer ces sources a des commentateurs tiers. Et je tiens a souligner que, pour l'instant, je ne vous ai pas encore vu faire la preuve que, quel qu'en soit votre parcours ou votre connaissance du processus editorial, votre autorite puisse avoir plus de valeur que celles des sources journalistiques. Si vous connaissez le processus editorial, cette Pull Request laisse quand meme a desirer de ce cote la...

**Pull request closed without merging**
