### PR TITLE
Insert new translations for Rufus 2.16

### PR DESCRIPTION
**Pull request by trinaldi**
Preparing for the new release, I've already made the new changes.

### CODE REVIEW

**Comment by NSbuilder** [comment]
I'm working on my translation and improving stuff, should be available soon.

**Comment by pbatard** [comment]
Okay. Let me know when it's done - no rush.

**Comment by pbatard** [comment]
Okay, since I'm releasing a new BETA version, I'm gonna pick your changes. If you still need to update it, feel free to create a new pull request.

PS: I corrected the "SAe" to "Se" in "SAe você obteve este arquivo da Internet...", as I assume this was a typoe

**Comment by trinaldi** [comment]
That's right, Pete

**Pull request closed without merging**
