### PR TITLE
Update el-GR.po

### PR DESCRIPTION
**Pull request by CrisBalGreece**
Add missing lines from MSG_307 to MSG_334.

### CODE REVIEW

**Comment by pbatard** [comment]
Thanks, but I'm afraid these lines are going to change for the next release, and there will be more added, therefore I am not ready to accept translation updates yet.

**Comment by CrisBalGreece** [comment]
> Thanks, but I'm afraid these lines are going to change for the next release, and there will be more added, therefore I am not ready to accept translation updates yet.

No prob my friend. I'll keep in mind for your next release -additions and I'll make them again Thanks for your hard work there..

**Comment by pbatard** [comment]
Closed with 8449accb5580a854045ebeb5e2fd505dd1b376ea (with my apologies, as I had forgotten this PR was available before somebody else volunteered).

**Comment by CrisBalGreece** [comment]
> Closed with [8449acc](https://github.com/pbatard/rufus/commit/8449accb5580a854045ebeb5e2fd505dd1b376ea) (with my apologies, as I had forgotten this PR was available before somebody else volunteered).

No prob. Keep moving bro..

**Pull request closed without merging**
